name: BibleProjector
version: 0.1.0
description: TodoMVC built with the polymer.dart package
environment:
  sdk: 'any'
dependencies:
  polymer: 'any'
dev_dependencies:
  unittest: 'any'
transformers:
- polymer:
    entry_points: web/index.html
